### ISSUE TITLE
How to turn off the log?

### ISSUE THREAD

**Issue by zhuwenbing** [Mr-Jos/namesilo_ddns_cli#1]
Hi, this shell is good for use. But I'm not good at the shell, and now I want to close the log, please help me, thank you!

**Comment by Mr-Jos** [comment]
You can discard logs by replacing line 28 : `LOG="/dev/null"`
However, it is not recommanded because the cache in the log will also be disabled. No cache means that Namesilo API will be requested for each running, and your IP may be banned by Namesilo if the frequency of your requesting is too high.
It's not worth worrying about the log size, since the log will be compressed and controled within 200 lines by default (line 31).
Therefore, the log file acts as a cache with latest useful logs more than a common log which records everything.

上面就留着给老外看吧。
若想丢弃日志，可把代码第28行改为：`LOG="/dev/null"`
但是非常不建议你这样做，因为日志里的缓存也被禁用了。没有缓存意味着每次运行脚本都要调用 Namesilo API ，如果频率太高就有可能被 Namesilo 封掉。
其实大可不必担心日志及其存储空间占用的问题，因为本脚本能够自动压缩和控制日志行数（默认最多200行，参见代码第31行）。
因此本脚本的日志就不能视为常规意义上的日志，应该更接近于含有最近日志的缓存文件。而缓存文件是各种DDNS控件必须要有的（至少要记一下当前的解析状态），我只不过让它同时发挥了更多作用。

如果只是个 Namesilo DDNS 的功能，100行代码足够了，那我这600行代码都折腾啥呢？还不是为了能在路由器里跑起来不用管嘛，所以设计基本思路就是无依赖、低负载、少请求。控制临时文件（日志/缓存/配置...）的存储空间和运行负载当然是要具备的基本功能之一了，比如说在我路由器上跑了一个月还不足100行日志（双域名每五分钟运行一次，实际换IP间隔约80h），这是因为绝大多数日志都被压缩掉了（IP没变化的日志），即便将来有更多日志也只会保留最近的200行。

**Comment by zhuwenbing** [comment]
好的，谢谢！
